#!/bin/sh

# SPDX-FileCopyrightText: 2025 Eli Array Minkoff
#
# SPDX-License-Identifier: 0BSD

set -e
cd "$(git rev-parse --show-toplevel)"

# fail with uncommitted changes - porcelain output will be empty if good to go
if git status --porcelain | grep -q .; then
    printf 'Uncommitted changes!\n' >&2
    exit 1
fi

# check for spelling mistakes
codespell
# check for missing or malformed license info - run silently by default, but on
# failure, run again with output
reuse lint -q || reuse lint

# ensure formatted
cargo fmt --check
# run general test suite
cargo test
# check for clippy issues
cargo clippy --tests -- -D warnings
# ensure that code coverage is at least 90%
cargo tarpaulin --fail-under 90

# test all single-backend builds one-by-one
for backend in arm64 s390x x86_64; do
    cargo clippy --no-default-features --features "$backend" -- -D warnings
    cargo test --no-default-features --features "$backend"
done
