#!/bin/sh

# SPDX-FileCopyrightText: 2025 Eli Array Minkoff
#
# SPDX-License-Identifier: 0BSD

set -e
cd "$(git rev-parse --show-toplevel)"

cargo test
cargo clippy --tests -- -D warnings

for backend in arm64 s390x x86_64; do
    cargo clippy --no-default-features --features "$backend" -- -D warnings
done
