# SPDX-FileCopyrightText: NONE
#
# SPDX-License-Identifier: 0BSD

[package]
name = "eambfc-rs"
version = "1.1.0"
edition = "2021"

[features]
default = ["arm64"]
arm64 = []

[profile.release]
lto = "thin"
codegen-units = 1
strip="symbols"
