# SPDX-FileCopyrightText: 2024 - 2026 Eli Array Minkoff
#
# SPDX-License-Identifier: 0BSD

[package]
name = "eambfc-rs"
version = "5.0.0-pre"
edition = "2024"

[features]
default = ["all_backends", "bintests", "disasmtests"]
all_backends = ["arm64", "riscv64", "s390x", "x86_64", "i386"]
arm64 = []
i386 = []
riscv64 = []
s390x = []
x86_64 = []
bintests = []
disasmtests = []

[lints.rust]
# don't warn on tarpaulin code coverage cfg conditions or custom cfgs
[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = ['cfg(tarpaulin_include)']

[lints.clippy]
# enable these categories with a negative priority, so that individual lints can
# be overridden
suspicious = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
# some clippy::restriction tests that I want enabled
deref_by_slicing = "warn"
empty_structs_with_brackets = "warn"
format_push_string = "warn"
if_then_some_else_none = "warn"
let_underscore_must_use = "warn"
allow_attributes_without_reason = "warn"
assertions_on_result_states = "warn"
dbg_macro = "warn"
same_name_method = "warn"
semicolon_outside_block = "warn"
exit = "warn"
unseparated_literal_suffix = "warn"
redundant_type_annotations = "warn"
field_scoped_visibility_modifiers = "warn"
missing_assert_message = "warn"

[profile.release]
lto = "thin"
codegen-units = 1
strip="symbols"

[dependencies]

[dev-dependencies]
test_macros = { path = "test_macros" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
tempfile = "3.15.0"
llvm-sys = { version = ">=191.0.0, <202.0.0", features = ["prefer-dynamic"] }
