# SPDX-FileCopyrightText: NONE
#
# SPDX-License-Identifier: 0BSD

[package]
name = "eambfc-rs"
version = "3.0.0"
edition = "2021"

[features]
default = ["arm64", "s390x"]
arm64 = []
s390x = []

[profile.release]
lto = "thin"
codegen-units = 1
strip="symbols"
