# SPDX-FileCopyrightText: 2025 Eli Array Minkoff
#
# SPDX-License-Identifier: 0BSD
[test_config]
name = "eambfc-rs"
locked = true
offline = true
engine = "Llvm"
test-timeout = "1m"
target-dir = ".tarpaulin"
skip-clean = true

[longopts_test]
name = "eambfc-rs"
locked = true
offline = true
engine = "Llvm"
test-timeout = "1m"
target-dir = ".tarpaulin"
skip-clean = true
features = "all_backends longopts"
