// SPDX-FileCopyrightText: 2024 - 2025 Eli Array Minkoff
//
// SPDX-License-Identifier: GPL-3.0-only

#[derive(Debug, Clone, Copy, PartialEq)]
enum ElfClass {
    #[cfg(have_32bit_targets)]
    ELFClass32 = 1,
    #[cfg(have_64bit_targets)]
    ELFClass64 = 2,
}

impl ElfClass {
    const fn ehdr_sz(self) -> u16 {
        match self {
            #[cfg(have_32bit_targets)]
            ElfClass::ELFClass32 => 52,
            #[cfg(have_64bit_targets)]
            ElfClass::ELFClass64 => 64,
        }
    }
    const fn phdr_sz(self) -> u16 {
        match self {
            #[cfg(have_32bit_targets)]
            ElfClass::ELFClass32 => 32,
            #[cfg(have_64bit_targets)]
            ElfClass::ELFClass64 => 56,
        }
    }
}

#[derive(Clone, Copy)]
pub(super) enum ByteOrdering {
    #[cfg(have_le_targets)]
    LittleEndian = 1,
    #[cfg(have_be_targets)]
    BigEndian = 2,
}

/// Enum of supported backends
#[derive(Debug, Clone, Copy, PartialEq)]
pub(crate) enum Backend {
    #[cfg(feature = "arm64")]
    Arm64,
    #[cfg(feature = "riscv64")]
    RiscV64,
    #[cfg(feature = "s390x")]
    S390x,
    #[cfg(feature = "x86_64")]
    X86_64,
}

impl Backend {
    /// Get the `e_machine` value for the architecture
    const fn e_machine(self) -> u16 {
        match self {
            #[cfg(feature = "arm64")]
            Self::Arm64 => 183,
            #[cfg(feature = "riscv64")]
            Self::RiscV64 => 243,
            #[cfg(feature = "s390x")]
            Self::S390x => 22,
            #[cfg(feature = "x86_64")]
            Self::X86_64 => 62,
        }
    }
    /// Get the `ElfClass` for the architecture
    const fn ei_class(self) -> ElfClass {
        match self {
            #[cfg(feature = "arm64")]
            Self::Arm64 => ElfClass::ELFClass64,
            #[cfg(feature = "riscv64")]
            Self::RiscV64 => ElfClass::ELFClass64,
            #[cfg(feature = "s390x")]
            Self::S390x => ElfClass::ELFClass64,
            #[cfg(feature = "x86_64")]
            Self::X86_64 => ElfClass::ELFClass64,
        }
    }

    /// Get the `ByteOrdering` for the architecture
    pub(super) const fn ei_data(self) -> ByteOrdering {
        match self {
            #[cfg(feature = "s390x")]
            Self::S390x => ByteOrdering::BigEndian,
            #[cfg(have_le_targets)]
            _ => ByteOrdering::LittleEndian,
        }
    }
}

impl std::fmt::Display for Backend {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> Result<(), std::fmt::Error> {
        write!(
            f,
            "{}",
            match *self {
                #[cfg(feature = "arm64")]
                Backend::Arm64 => "arm64",
                #[cfg(feature = "riscv64")]
                Backend::RiscV64 => "riscv64",
                #[cfg(feature = "s390x")]
                Backend::S390x => "s390x",
                #[cfg(feature = "x86_64")]
                Backend::X86_64 => "x86_64",
            }
        )
    }
}

impl Default for Backend {
    fn default() -> Self {
        match env!("EAMBFC_DEFAULT_ARCH") {
            #[cfg(feature = "arm64")]
            "arm64" => Backend::Arm64,
            #[cfg(feature = "riscv64")]
            "riscv64" => Backend::RiscV64,
            #[cfg(feature = "s390x")]
            "s390x" => Backend::S390x,
            #[cfg(feature = "x86_64")]
            "x86_64" => Backend::X86_64,
            _ => unreachable!("build.rs sets this to valid values only"),
        }
    }
}

impl From<Backend> for [u8; 16] {
    fn from(e_arch: Backend) -> [u8; 16] {
        #[rustfmt::skip]
        let arr: [u8; 16] = [
            // magic bytes
            0x7f, b'E', b'L', b'F',
            // 32 or 64 bit
            e_arch.ei_class() as u8,
            // byte ordering for architecture
            e_arch.ei_data() as u8,
            // Version of an ELF file - only valid value
            1,
            // SYSV ABI with unspecified version
            0, 0,
            // padding bytes
            0, 0, 0, 0, 0, 0, 0
        ];
        arr
    }
}

/// The information needed to construct an ELF Ehdr, not including information which is always the
/// same across all ELF executables generated by eambfc-rs
pub(super) struct BinInfo {
    /// The target backend - used to determine the pointer size, byte ordering, and `e_machine`
    /// value for the Ehdr
    pub arch: Backend,
    /// The program entry point
    pub entry: u64,
    /// The backend-specific Ehdr flags
    pub flags: u32,
}

/// The information needed to construct and ELF Phdr entry, not including information which is
/// always the same across both of the segments used across all ELF executables generated by
/// eambfc-rs
pub(super) struct SegmentInfo {
    /// Used to determine byte ordering and register size
    pub arch: Backend,
    /// Segment `p_flags` value
    pub flags: u32,
    /// Segment `p_vaddr` value
    pub vaddr: u64,
    /// Segment `p_memsz` value
    pub size: u64,
    /// If true, use `size` as the `p_filesz` value. Otherwise, use `0` as the `p_filesz` value.
    pub file_backed: bool,
    /// Segment `p_align` value
    pub align: u32,
}

/// Pass a `BinInfo` binding, followed by `LE` or `BE` for little-endian or big-endian backends
/// respectively, then `32` for 32-bit or `64` for 64-bit backends respectively.
///
/// It will use the appropriate struct member sizes and write the bytes for the appropriate byte
/// ordering for the given register size and byte ordering combo.
///
/// # Example
///
/// ```no_run
/// let item: BinInfo = { ... };
/// serialize_ehdr!(item, LE, 64)
/// ```
// While ugly, it gets the job done without repeating code for different backend register sizes or
// byte orderings.
macro_rules! serialize_ehdr {
    // Variants meant for actual use
    ($item: ident, LE, 64) => {{ serialize_ehdr!(<internal> $item, to_le_bytes, u64) }};
    ($item: ident, BE, 64) => {{ serialize_ehdr!(<internal> $item, to_be_bytes, u64) }};
    ($item: ident, LE, 32) => {{ serialize_ehdr!(<internal> $item, to_le_bytes, u32) }};
    ($item: ident, BE, 32) => {{ serialize_ehdr!(<internal> $item, to_be_bytes, u32) }};
    // Internal implementation of the serialization
    (<internal> $item: ident, $func: ident, $addr_type: ty) => {{
        let mut v = Vec::with_capacity($item.arch.ei_class().ehdr_sz().into());
        v.extend(<[u8; 16]>::from($item.arch));
        // e_type = ET_EXEC
        v.extend(u16::$func(2));
        // e_machine (provided by `$item`)
        v.extend($item.arch.e_machine().$func());
        // e_version = 1
        v.extend(u32::$func(1));
        // e_entry (provided by `$item`)
        v.extend(
            <$addr_type>::try_from($item.entry)
                .expect("Validated tape size")
                .$func(),
        );
        // e_phoff is always equal to e_ehsize, which depends on the architecture class
        v.extend(<$addr_type>::from($item.arch.ei_class().ehdr_sz()).$func());
        // e_shoff is always zero
        v.extend(<$addr_type>::$func(0));
        // e_flags (provided by `$item`)
        v.extend($item.flags.$func());
        // e_ehsize depends on the architecture class
        v.extend($item.arch.ei_class().ehdr_sz().$func());
        // e_phentsize depends on the architecture class
        v.extend($item.arch.ei_class().phdr_sz().$func());
        // e_phnum is always 2: 1 for the code segment and 1 for the tape segment
        v.extend(u16::$func(2));
        // e_shentsize is zero as there is no section header table
        v.extend(u16::$func(0));
        // e_shnum is zero as there is no section header table
        v.extend(u16::$func(0));
        // e_shstrndx is zero as there is no section header table
        v.extend(u16::$func(0));
        v
    }};
}

/// pass a `Phdr` binding, followed by `LE` or `BE` for little or big-endian backends respecitvely,
/// followed by `64` or `32` for 64-bit or 32-bit backends respectively.
///
/// It will use the appropriate struct member sizes and order for the provided size, and write the
/// bytes of the members in the provided byte ordering
macro_rules! serialize_phdr {
    // Variants meant for actual use
    ($item: ident, LE, $sz: tt) => {{ serialize_phdr!(<internal> $item, to_le_bytes, $sz) }};
    ($item: ident, BE, $sz: tt) => {{ serialize_phdr!(<internal> $item, to_be_bytes, $sz) }};

    // Items in 64-bit order
    (<internal> $item:ident, $func:ident, 64) => {{
        let mut v = Vec::with_capacity(56);
        // p_type is always `PT_LOAD`
        v.extend(u32::$func(1));
        // p_flags (provided by `$item`)
        v.extend($item.flags.$func());
        // p_offset is 0 either because there's no backing data in file or it's the whole file
        v.extend(u64::$func(0));
        // p_vaddr (provided by `$item`)
        v.extend($item.vaddr.$func());
        // p_paddr is always zero
        v.extend(u64::$func(0));
        // p_filesz (provided by `$item`)
        v.extend(if $item.file_backed { $item.size } else { 0 }.$func());
        // p_memsz (provided by `$item`)
        v.extend($item.size.$func());
        // p_align (provided by `$item`) (need to extend to 64 bits)
        v.extend(u64::from($item.align).$func());
        v
    }};

    (<internal> $item:ident, $func:ident, 32) => {{
        let mut v = Vec::with_capacity(56);
        // p_type is always `PT_LOAD`
        v.extend(u32::$func(1));
        // p_offset is 0 either because there's no backing data in file or it's the whole file
        v.extend(u32::$func(0));
        // p_vaddr (provided by `$item`)
        v.extend(u32::try_from($item.vaddr).expect("Validated vaddr").$func());
        // p_paddr is always zero
        v.extend(u32::$func(0));
        // p_filesz (provided by `$item`)
        let size: u32 = $item.size.try_into().expect("validated size");
        v.extend(if $item.file_backed { size } else { 0 }.$func());
        // p_memsz (provided by `$item`)
        v.extend(u32::try_from($item.size).expect("Validated size").$func());
        // p_flags (provided by `$item`)
        v.extend($item.flags.$func());
        // p_align (provided by `$item`)
        v.extend($item.align.$func());
        v
    }};
}

impl From<BinInfo> for Vec<u8> {
    fn from(item: BinInfo) -> Self {
        match (item.arch.ei_class(), item.arch.ei_data()) {
            #[cfg(all(have_64bit_targets, have_le_targets))]
            (ElfClass::ELFClass64, ByteOrdering::LittleEndian) => serialize_ehdr!(item, LE, 64),
            #[cfg(all(have_32bit_targets, have_le_targets))]
            (ElfClass::ELFClass32, ByteOrdering::LittleEndian) => serialize_ehdr!(item, LE, 32),
            #[cfg(all(have_64bit_targets, have_be_targets))]
            (ElfClass::ELFClass64, ByteOrdering::BigEndian) => serialize_ehdr!(item, BE, 64),
            #[cfg(all(have_32bit_targets, have_be_targets))]
            (ElfClass::ELFClass32, ByteOrdering::BigEndian) => serialize_ehdr!(item, BE, 64),
        }
    }
}

// as endian-ness is not communicated in Phdr entries, it's added to the Phdr struct used within
// eambfc-rs for this.
impl From<SegmentInfo> for Vec<u8> {
    fn from(item: SegmentInfo) -> Self {
        match item.arch.ei_data() {
            #[cfg(any(feature = "arm64", feature = "riscv64", feature = "x86_64"))]
            ByteOrdering::LittleEndian => serialize_phdr!(item, LE, 64),
            #[cfg(feature = "s390x")]
            ByteOrdering::BigEndian => serialize_phdr!(item, BE, 64),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::Backend;
    #[test]
    fn display_elfarch() {
        #[cfg(feature = "arm64")]
        assert_eq!(format!("{}", Backend::Arm64), String::from("arm64"));
        #[cfg(feature = "riscv64")]
        assert_eq!(format!("{}", Backend::RiscV64), String::from("riscv64"));
        #[cfg(feature = "s390x")]
        assert_eq!(format!("{}", Backend::S390x), String::from("s390x"));
        #[cfg(feature = "x86_64")]
        assert_eq!(format!("{}", Backend::X86_64), String::from("x86_64"));
    }
}
